name: C/C++ CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: sudo apt -y install meson clang gcc-mingw-w64-x86-64-win32
    - name: make
      run: make build

